const data = [ { product_name: 'Hilti Orbital Sander',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_01.jpg',
    review_stars: 4,
    review_count: 8,
    price: 38.12,
    product_description: 'donec ut dolor morbi vel lectus in quam fringilla rhoncus' },
  { product_name: 'Hilti Lathe',
    //image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_2.jpg',
    review_stars: 5,
    review_count: 6,
    price: 185.15,
    product_description:
     'quam pede lobortis ligula sit amet eleifend pede libero quis' },
  { product_name: 'Bosch Table Saw',
    //image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_3.jpg',
    review_stars: 3,
    review_count: 15,
    price: 153.55,
    product_description: 'nulla tellus in sagittis dui vel nisl duis' },
  { product_name: 'Bosch Power Screwdriver',
    //image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_4.jpg',
    review_stars: 1,
    review_count: 7,
    price: 192.21,
    product_description: 'blandit mi in porttitor pede' },
  { product_name: 'Dewalt Rotary Tool',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_5.jpg',
    review_stars: 4,
    review_count: 16,
    price: 2.25,
    product_description: 'in sagittis dui vel nisl duis ac nibh fusce lacus' },
  { product_name: 'Bosch Shop Vacuum',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_6.jpg',
    review_stars: 4,
    review_count: 1,
    price: 182.15,
    product_description: 'pede lobortis ligula sit amet eleifend pede libero' },
  { product_name: 'Hilti Nail Gun',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_7.jpg',
    review_stars: 1,
    review_count: 6,
    price: 195.50,
    product_description:
     'quis orci nullam molestie nibh in lectus pellentesque at nulla' },
  { product_name: 'Craftsman Chop Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_8.jpg',
    review_stars: 3,
    review_count: 1,
    price: 115.49,
    product_description: 'eu nibh quisque id justo sit amet sapien dignissim' },
  { product_name: 'Dewalt Jointer',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_9.jpg',
    review_stars: 5,
    review_count: 3,
    price: 60.35,
    product_description: 'felis donec semper sapien a libero nam dui proin leo' },
  { product_name: 'Hilti Chainsaw',
    // image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_10.jpg',
    review_stars: 3,
    review_count: 12,
    price: 45.21,
    product_description: 'amet erat nulla tempus vivamus in felis eu' },
  { product_name: 'Bosch Reciprocating Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_11.png',
    review_stars: 2,
    review_count: 1,
    price: 179.32,
    product_description: 'dictumst maecenas ut massa quis' },
  { product_name: 'Craftsman Circular Saw',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_12.jpg',
    review_stars: 2,
    review_count: 9,
    price: 83.25,
    product_description:
     'pellentesque quisque porta volutpat erat quisque erat eros viverra' },
  { product_name: 'Bosch Angle Grinder',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_13.jpg',
    review_stars: 1,
    review_count: 17,
    price: 195.22,
    product_description: 'luctus nec molestie sed justo pellentesque' },
  { product_name: 'Craftsman Heat Gun',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_14.jpg',
    review_stars: 3,
    review_count: 5,
    price: 139.26,
    product_description: 'rutrum rutrum neque aenean auctor gravida sem praesent' },
  { product_name: 'Bosch Jigsaw',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_15.jpg',
    review_stars: 4,
    review_count: 11,
    price: 142.69,
    product_description: 'iaculis justo in hac habitasse platea' },
  { product_name: 'Hilti Chop Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_16.jpg',
    review_stars: 4,
    review_count: 19,
    price: 3.52,
    product_description: 'quam a odio in hac habitasse' },
  { product_name: 'Craftsman Biscuit Joiner',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_17.jpg',
    review_stars: 3,
    review_count: 4,
    price: 11.70,
    product_description: 'amet eros suspendisse accumsan tortor' },
  { product_name: 'Bosch Biscuit Joiner',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_18.jpg',
    review_stars: 2,
    review_count: 9,
    price: 162.05,
    product_description: 'tempor convallis nulla neque libero convallis' },
  { product_name: 'Dewalt Table Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_19.jpg',
    review_stars: 2,
    review_count: 1,
    price: 118.51,
    product_description: 'dolor quis odio consequat varius' },
  { product_name: 'Hilti Biscuit Joiner',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_20.jpg',
    review_stars: 5,
    review_count: 11,
    price: 100.91,
    product_description: 'felis eu sapien cursus vestibulum proin eu mi nulla' },
  { product_name: 'Bosch Miter Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_21.jpg',
    review_stars: 3,
    review_count: 13,
    price: 183.79,
    product_description: 'lorem id ligula suspendisse ornare consequat lectus in est' },
  { product_name: 'Hilti Hammer Drill',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_22.jpg',
    review_stars: 1,
    review_count: 19,
    price: 30.08,
    product_description: 'ante ipsum primis in faucibus orci luctus' },
  { product_name: 'Craftsman Disc Sander',
    // image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_23.jpg',
    review_stars: 2,
    review_count: 11,
    price: 98.35,
    product_description: 'nec euismod scelerisque quam turpis adipiscing lorem' },
  { product_name: 'Craftsman Nail Gun',
    // image_src: 'http://dummyimage.com/150x150.bmp/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_24.jpg',
    review_stars: 3,
    review_count: 3,
    price: 50.75,
    product_description: 'odio justo sollicitudin ut suscipit a feugiat et eros' },
  { product_name: 'Bosch Disc Sander',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_25.jpg',
    review_stars: 1,
    review_count: 15,
    price: 90.14,
    product_description: 'in tempus sit amet sem fusce consequat nulla nisl nunc' },
  { product_name: 'Dewalt Scroll Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_26.jpg',
    review_stars: 5,
    review_count: 3,
    price: 53.96,
    product_description: 'vestibulum rutrum rutrum neque aenean auctor gravida' },
  { product_name: 'Craftsman Miter Saw',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_27.jpg',
    review_stars: 4,
    review_count: 14,
    price: 61.29,
    product_description: 'proin risus praesent lectus vestibulum quam sapien varius' },
  { product_name: 'Craftsman Shop Vacuum',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_28.jpg',
    review_stars: 4,
    review_count: 20,
    price: 9.81,
    product_description: 'consequat in consequat ut nulla sed accumsan' },
  { product_name: 'Hilti Air Compressor',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_29.jpg',
    review_stars: 1,
    review_count: 6,
    price: 71.56,
    product_description: 'sit amet lobortis sapien sapien non mi' },
  { product_name: 'Hilti Table Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_30.jpg',
    review_stars: 4,
    review_count: 14,
    price: 147.54,
    product_description: 'varius ut blandit non interdum in ante vestibulum ante' },
  { product_name: 'Dewalt Impact Driver',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_31.png',
    review_stars: 5,
    review_count: 19,
    price: 149.36,
    product_description: 'nullam porttitor lacus at turpis donec' },
  { product_name: 'Craftsman Jointer',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_32.jpeg',
    review_stars: 1,
    review_count: 5,
    price: 84.22,
    product_description: 'ut dolor morbi vel lectus in' },
  { product_name: 'Craftsman Rotary Tool',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_33.jpeg',
    review_stars: 3,
    review_count: 11,
    price: 181.21,
    product_description:
     'iaculis justo in hac habitasse platea dictumst etiam faucibus cursus' },
  { product_name: 'Hilti Jigsaw',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_34.jpeg',
    review_stars: 3,
    review_count: 20,
    price: 3.96,
    product_description: 'at dolor quis odio consequat' },
  { product_name: 'Bosch Rotary Tool',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_35.jpeg',
    review_stars: 5,
    review_count: 12,
    price: 129.09,
    product_description: 'gravida sem praesent id massa id nisl venenatis lacinia' },
  { product_name: 'Hilti Rotary Tool',
    // image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_36.jpeg',
    review_stars: 4,
    review_count: 18,
    price: 184.40,
    product_description: 'nulla dapibus dolor vel est' },
  { product_name: 'Hilti Shop Vacuum',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_37.jpeg',
    review_stars: 5,
    review_count: 4,
    price: 156.59,
    product_description: 'primis in faucibus orci luctus et' },
  { product_name: 'Craftsman Reciprocating Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_38.jpeg',
    review_stars: 3,
    review_count: 9,
    price: 23.38,
    product_description: 'nullam varius nulla facilisi cras non velit nec' },
  { product_name: 'Hilti Miter Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_39.jpeg',
    review_stars: 1,
    review_count: 20,
    price: 42.45,
    product_description: 'vehicula consequat morbi a ipsum integer a nibh' },
  { product_name: 'Craftsman Air Compressor',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_40.jpeg',
    review_stars: 1,
    review_count: 12,
    price: 194.26,
    product_description: 'rutrum neque aenean auctor gravida' },
  { product_name: 'Dewalt Biscuit Joiner',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_41.jpeg',
    review_stars: 2,
    review_count: 4,
    price: 35.26,
    product_description: 'velit donec diam neque vestibulum' },
  { product_name: 'Dewalt Radial Arm Saw',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_42.jpeg',
    review_stars: 1,
    review_count: 18,
    price: 130.45,
    product_description: 'orci eget orci vehicula condimentum curabitur in' },
  { product_name: 'Dewalt Disc Sander',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_43.jpeg',
    review_stars: 3,
    review_count: 5,
    price: 64.27,
    product_description: 'augue vel accumsan tellus nisi eu orci mauris lacinia' },
  { product_name: 'Bosch Belt Sander',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_44.jpeg',
    review_stars: 5,
    review_count: 16,
    price: 110.75,
    product_description: 'nec sem duis aliquam convallis nunc proin' },
  { product_name: 'Dewalt Air Compressor',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_45.jpeg',
    review_stars: 4,
    review_count: 18,
    price: 53.12,
    product_description: 'mauris morbi non lectus aliquam sit amet diam in' },
  { product_name: 'Craftsman Chainsaw',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_46.jpeg',
    review_stars: 5,
    review_count: 7,
    price: 185.78,
    product_description: 'nullam varius nulla facilisi cras non velit nec nisi' },
  { product_name: 'Hilti Radial Arm Saw',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_47.jpeg',
    review_stars: 5,
    review_count: 13,
    price: 43.46,
    product_description:
     'penatibus et magnis dis parturient montes nascetur ridiculus mus etiam' },
  { product_name: 'Bosch Chainsaw',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_48.jpeg',
    review_stars: 5,
    review_count: 14,
    price: 8.10,
    product_description: 'massa donec dapibus duis at velit eu' },
  { product_name: 'Craftsman Jigsaw',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_49.jpeg',
    review_stars: 5,
    review_count: 18,
    price: 103.86,
    product_description: 'primis in faucibus orci luctus et ultrices posuere' },
  { product_name: 'Bosch Circular Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_50.jpeg',
    review_stars: 5,
    review_count: 15,
    price: 140.46,
    product_description: 'ante ipsum primis in faucibus' },
  { product_name: 'Bosch Hammer Drill',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_51.jpeg',
    review_stars: 4,
    review_count: 20,
    price: 44.75,
    product_description: 'integer non velit donec diam neque vestibulum eget' },
  { product_name: 'Hilti Reciprocating Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_52.jpeg',
    review_stars: 3,
    review_count: 16,
    price: 190.32,
    product_description: 'ultrices posuere cubilia curae donec pharetra magna' },
  { product_name: 'Dewalt Chop Saw',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_53.jpeg',
    review_stars: 1,
    review_count: 3,
    price: 94.38,
    product_description: 'eros suspendisse accumsan tortor quis turpis sed ante' },
  { product_name: 'Bosch Lathe',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_54.jpeg',
    review_stars: 3,
    review_count: 9,
    price: 160.43,
    product_description: 'vitae quam suspendisse potenti nullam porttitor' },
  { product_name: 'Dewalt Impact Wrench',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_55.jpeg',
    review_stars: 5,
    review_count: 10,
    price: 63.45,
    product_description: 'nec euismod scelerisque quam turpis' },
  { product_name: 'Bosch Jointer',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_56.jpeg',
    review_stars: 1,
    review_count: 8,
    price: 92.26,
    product_description: 'eros viverra eget congue eget semper rutrum' },
  { product_name: 'Craftsman Lathe',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_57.jpeg',
    review_stars: 4,
    review_count: 2,
    price: 86.00,
    product_description: 'quis turpis eget elit sodales scelerisque' },
  { product_name: 'Craftsman Hammer Drill',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_58.gif',
    review_stars: 4,
    review_count: 2,
    price: 136.04,
    product_description: 'nibh in quis justo maecenas rhoncus aliquam' },
  { product_name: 'Bosch Air Compressor',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_59.jpg',
    review_stars: 5,
    review_count: 6,
    price: 86.83,
    product_description:
     'aenean fermentum donec ut mauris eget massa tempor convallis nulla' },
  { product_name: 'Hilti Disc Sander',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_60.jpg',
    review_stars: 2,
    review_count: 7,
    price: 117.03,
    product_description:
     'pellentesque eget nunc donec quis orci eget orci vehicula condimentum' },
  { product_name: 'Craftsman Scroll Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_61.jpg',
    review_stars: 4,
    review_count: 8,
    price: 56.82,
    product_description: 'neque aenean auctor gravida sem praesent id massa id nisl' },
  { product_name: 'Dewalt Lathe',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_62.jpg',
    review_stars: 2,
    review_count: 10,
    price: 44.71,
    product_description: 'id sapien in sapien iaculis congue vivamus metus' },
  { product_name: 'Bosch Radial Arm Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_63.jpg',
    review_stars: 3,
    review_count: 11,
    price: 69.61,
    product_description: 'natoque penatibus et magnis dis parturient montes nascetur' },
  { product_name: 'Dewalt Angle Grinder',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_64.jpg',
    review_stars: 2,
    review_count: 20,
    price: 13.84,
    product_description:
     'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum' },
  { product_name: 'Bosch Scroll Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_65.jpg',
    review_stars: 1,
    review_count: 10,
    price: 81.64,
    product_description:
     'parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum' },
  { product_name: 'Dewalt Nail Gun',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_66.jpg',
    review_stars: 2,
    review_count: 17,
    price: 1.35,
    product_description:
     'consequat metus sapien ut nunc vestibulum ante ipsum primis in' },
  { product_name: 'Hilti Angle Grinder',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_67.jpg',
    review_stars: 3,
    review_count: 19,
    price: 149.29,
    product_description:
     'vestibulum vestibulum ante ipsum primis in faucibus orci luctus et' },
  { product_name: 'Dewalt Power Screwdriver',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_68.jpg',
    review_stars: 2,
    review_count: 13,
    price: 182.24,
    product_description: 'vel nisl duis ac nibh fusce lacus purus aliquet' },
  { product_name: 'Hilti Heat Gun',
    // image_src: 'http://dummyimage.com/150x150.jpg/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_69.jpg',
    review_stars: 5,
    review_count: 18,
    price: 111.35,
    product_description: 'congue etiam justo etiam pretium iaculis justo in hac' },
  { product_name: 'Craftsman Belt Sander',
    // image_src: 'http://dummyimage.com/150x150.png/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_70.jpg',
    review_stars: 4,
    review_count: 1,
    price: 99.82,
    product_description:
     'ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus' },
  { product_name: 'Dewalt Orbital Sander',
    // image_src: 'http://dummyimage.com/150x150.bmp/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_71.jpg',
    review_stars: 3,
    review_count: 20,
    price: 122.76,
    product_description: 'nonummy integer non velit donec diam' },
  { product_name: 'Dewalt Belt Sander',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_72.jpg',
    review_stars: 2,
    review_count: 10,
    price: 43.46,
    product_description: 'vel augue vestibulum ante ipsum' },
  { product_name: 'Hilti Scroll Saw',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_73.png',
    review_stars: 1,
    review_count: 19,
    price: 163.98,
    product_description: 'sapien urna pretium nisl ut volutpat sapien' },
  { product_name: 'Hilti Impact Driver',
    // image_src: 'http://dummyimage.com/150x150.bmp/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_74.jpg',
    review_stars: 5,
    review_count: 4,
    price: 161.25,
    product_description: 'leo maecenas pulvinar lobortis est phasellus sit' },
  { product_name: 'Dewalt Shop Vacuum',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_75.jpg',
    review_stars: 2,
    review_count: 7,
    price: 91.90,
    product_description:
     'in faucibus orci luctus et ultrices posuere cubilia curae duis' },
  { product_name: 'Dewalt Chainsaw',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_76.jpg',
    review_stars: 3,
    review_count: 7,
    price: 139.72,
    product_description:
     'pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus' },
  { product_name: 'Dewalt Reciprocating Saw',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_77.png',
    review_stars: 4,
    review_count: 13,
    price: 24.41,
    product_description:
     'sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus' },
  { product_name: 'Hilti Power Screwdriver',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_78.jpeg',
    review_stars: 4,
    review_count: 3,
    price: 189.55,
    product_description:
     'ante vivamus tortor duis mattis egestas metus aenean fermentum' },
  { product_name: 'Craftsman Power Screwdriver',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_79.jpeg',
    review_stars: 2,
    review_count: 3,
    price: 22.89,
    product_description:
     'vestibulum vestibulum ante ipsum primis in faucibus orci luctus' },
  { product_name: 'Craftsman Impact Driver',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_80.jpeg',
    review_stars: 4,
    review_count: 1,
    price: 132.13,
    product_description: 'aliquet pulvinar sed nisl nunc rhoncus' },
  { product_name: 'Craftsman Table Saw',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_81.jpeg',
    review_stars: 2,
    review_count: 18,
    price: 50.40,
    product_description: 'nulla nisl nunc nisl duis bibendum felis sed' },
  { product_name: 'Dewalt Jigsaw',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_82.jpeg',
    review_stars: 4,
    review_count: 18,
    price: 77.47,
    product_description: 'eros vestibulum ac est lacinia' },
  { product_name: 'Dewalt Heat Gun',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_83.jpeg',
    review_stars: 3,
    review_count: 18,
    price: 105.75,
    product_description: 'nulla elit ac nulla sed vel' },
  { product_name: 'Hilti Belt Sander',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_84.jpeg',
    review_stars: 4,
    review_count: 6,
    price: 23.56,
    product_description: 'in hac habitasse platea dictumst' },
  { product_name: 'Dewalt Hammer Drill',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_85.jpeg',
    review_stars: 3,
    review_count: 1,
    price: 139.69,
    product_description: 'at velit eu est congue elementum in hac' },
  { product_name: 'Hilti Jointer',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_86.jpeg',
    review_stars: 3,
    review_count: 19,
    price: 19.58,
    product_description: 'suscipit ligula in lacus curabitur at ipsum' },
  { product_name: 'Bosch Heat Gun',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_87.jpeg',
    review_stars: 2,
    review_count: 8,
    price: 64.07,
    product_description: 'ridiculus mus etiam vel augue vestibulum rutrum' },
  { product_name: 'Craftsman Angle Grinder',
    // image_src: 'http://dummyimage.com/150x150.jpg/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_88.jpeg',
    review_stars: 5,
    review_count: 5,
    price: 22.15,
    product_description: 'malesuada in imperdiet et commodo' },
  { product_name: 'Hilti Impact Wrench',
    // image_src: 'http://dummyimage.com/150x150.png/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_89.jpeg',
    review_stars: 1,
    review_count: 14,
    price: 55.85,
    product_description: 'ut dolor morbi vel lectus in quam fringilla rhoncus' },
  { product_name: 'Craftsman Impact Wrench',
    // image_src: 'http://dummyimage.com/150x150.png/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_90.png',
    review_stars: 4,
    review_count: 1,
    price: 75.30,
    product_description: 'orci pede venenatis non sodales sed' },
  { product_name: 'Craftsman Radial Arm Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_91.jpg',
    review_stars: 4,
    review_count: 3,
    price: 199.91,
    product_description:
     'elementum ligula vehicula consequat morbi a ipsum integer a nibh' },
  { product_name: 'Dewalt Circular Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_92.jpg',
    review_stars: 5,
    review_count: 14,
    price: 168.08,
    product_description: 'vestibulum ante ipsum primis in faucibus orci luctus et' },
  { product_name: 'Bosch Orbital Sander',
    // image_src: 'http://dummyimage.com/150x150.bmp/ff4444/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_93.jpg',
    review_stars: 2,
    review_count: 2,
    price: 75.09,
    product_description: 'nibh in quis justo maecenas rhoncus aliquam lacus' },
  { product_name: 'Bosch Nail Gun',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_94.jpg',
    review_stars: 2,
    review_count: 1,
    price: 141.65,
    product_description: 'libero nullam sit amet turpis elementum ligula vehicula' },
  { product_name: 'Craftsman Orbital Sander',
    // image_src: 'http://dummyimage.com/150x150.bmp/cc0000/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_95.jpg',
    review_stars: 4,
    review_count: 9,
    price: 118.54,
    product_description: 'nonummy integer non velit donec diam neque vestibulum eget' },
  { product_name: 'Bosch Chop Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/dddddd/000000',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_96.jpg',
    review_stars: 3,
    review_count: 3,
    price: 16.70,
    product_description: 'platea dictumst morbi vestibulum velit id pretium' },
  { product_name: 'Bosch Impact Wrench',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_97.jpg',
    review_stars: 3,
    review_count: 1,
    price: 6.52,
    product_description: 'dapibus duis at velit eu est congue' },
  { product_name: 'Bosch Impact Driver',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_98.jpg',
    review_stars: 3,
    review_count: 2,
    price: 104.82,
    product_description:
     'viverra dapibus nulla suscipit ligula in lacus curabitur at' },
  { product_name: 'Hilti Circular Saw',
    // image_src: 'http://dummyimage.com/150x150.jpg/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_99.jpg',
    review_stars: 5,
    review_count: 3,
    price: 69.54,
    product_description: 'lectus in est risus auctor sed tristique in tempus' },
  { product_name: 'Dewalt Miter Saw',
    // image_src: 'http://dummyimage.com/150x150.png/5fa2dd/ffffff',
    image_src: 'https://s3.amazonaws.com/fec-similar-options/product_100.jpg',
    review_stars: 2,
    review_count: 18,
    price: 171.26,
    product_description: 'turpis eget elit sodales scelerisque mauris sit amet eros' } ]

module.exports = data;


// from mockaroo
// const data = 
// [{"product_name":"Dik, kirk's dik","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":4,"review_count":8,"price":38.12,"product_description":"donec ut dolor morbi vel lectus in quam fringilla rhoncus"},
// {"product_name":"Eagle, bald","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":5,"review_count":6,"price":185.15,"product_description":"quam pede lobortis ligula sit amet eleifend pede libero quis"},
// {"product_name":"Starling, cape","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":3,"review_count":15,"price":153.55,"product_description":"nulla tellus in sagittis dui vel nisl duis"},
// {"product_name":"Great white pelican","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":1,"review_count":7,"price":192.21,"product_description":"blandit mi in porttitor pede"},
// {"product_name":"Arctic fox","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":4,"review_count":16,"price":2.25,"product_description":"in sagittis dui vel nisl duis ac nibh fusce lacus"},
// {"product_name":"Cheetah","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":4,"review_count":1,"price":182.15,"product_description":"pede lobortis ligula sit amet eleifend pede libero"},
// {"product_name":"Cat, african wild","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":1,"review_count":6,"price":195.5,"product_description":"quis orci nullam molestie nibh in lectus pellentesque at nulla"},
// {"product_name":"Nilgai","image_src":"http://dummyimage.com/150x150.bmp/ff4444/ffffff","review_stars":3,"review_count":1,"price":115.49,"product_description":"eu nibh quisque id justo sit amet sapien dignissim"},
// {"product_name":"Bear, polar","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":5,"review_count":3,"price":60.35,"product_description":"felis donec semper sapien a libero nam dui proin leo"},
// {"product_name":"Spotted wood sandpiper","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":3,"review_count":12,"price":45.21,"product_description":"amet erat nulla tempus vivamus in felis eu"},
// {"product_name":"Ibis, puna","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":2,"review_count":1,"price":179.32,"product_description":"dictumst maecenas ut massa quis"},
// {"product_name":"Peccary, white-lipped","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":2,"review_count":9,"price":83.25,"product_description":"pellentesque quisque porta volutpat erat quisque erat eros viverra"},
// {"product_name":"Raccoon dog","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":1,"review_count":17,"price":195.22,"product_description":"luctus nec molestie sed justo pellentesque"},
// {"product_name":"Brown lemur","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":3,"review_count":5,"price":139.26,"product_description":"rutrum rutrum neque aenean auctor gravida sem praesent"},
// {"product_name":"Paradoxure","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":4,"review_count":11,"price":142.69,"product_description":"iaculis justo in hac habitasse platea"},
// {"product_name":"Macaw, blue and gold","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":4,"review_count":19,"price":3.52,"product_description":"quam a odio in hac habitasse"},
// {"product_name":"Duck, mountain","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":3,"review_count":4,"price":11.7,"product_description":"amet eros suspendisse accumsan tortor"},
// {"product_name":"Woodchuck","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":2,"review_count":9,"price":162.05,"product_description":"tempor convallis nulla neque libero convallis"},
// {"product_name":"Hartebeest, coke's","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":2,"review_count":1,"price":118.51,"product_description":"dolor quis odio consequat varius"},
// {"product_name":"Boa, emerald green tree","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":5,"review_count":11,"price":100.91,"product_description":"felis eu sapien cursus vestibulum proin eu mi nulla"},
// {"product_name":"Tiger","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":3,"review_count":13,"price":183.79,"product_description":"lorem id ligula suspendisse ornare consequat lectus in est"},
// {"product_name":"Armadillo, nine-banded","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":1,"review_count":19,"price":30.08,"product_description":"ante ipsum primis in faucibus orci luctus"},
// {"product_name":"Red-necked wallaby","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":2,"review_count":11,"price":98.35,"product_description":"nec euismod scelerisque quam turpis adipiscing lorem"},
// {"product_name":"Yellow-brown sungazer","image_src":"http://dummyimage.com/150x150.bmp/ff4444/ffffff","review_stars":3,"review_count":3,"price":50.75,"product_description":"odio justo sollicitudin ut suscipit a feugiat et eros"},
// {"product_name":"Red squirrel","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":1,"review_count":15,"price":90.14,"product_description":"in tempus sit amet sem fusce consequat nulla nisl nunc"},
// {"product_name":"Slender-billed cockatoo","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":5,"review_count":3,"price":53.96,"product_description":"vestibulum rutrum rutrum neque aenean auctor gravida"},
// {"product_name":"Hottentot teal","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":4,"review_count":14,"price":61.29,"product_description":"proin risus praesent lectus vestibulum quam sapien varius"},
// {"product_name":"Rhinoceros, white","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":4,"review_count":20,"price":9.81,"product_description":"consequat in consequat ut nulla sed accumsan"},
// {"product_name":"Rhesus macaque","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":1,"review_count":6,"price":71.56,"product_description":"sit amet lobortis sapien sapien non mi"},
// {"product_name":"Ground monitor (unidentified)","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":4,"review_count":14,"price":147.54,"product_description":"varius ut blandit non interdum in ante vestibulum ante"},
// {"product_name":"Shelduck, european","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":5,"review_count":19,"price":149.36,"product_description":"nullam porttitor lacus at turpis donec"},
// {"product_name":"Common wolf","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":1,"review_count":5,"price":84.22,"product_description":"ut dolor morbi vel lectus in"},
// {"product_name":"Seven-banded armadillo","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":3,"review_count":11,"price":181.21,"product_description":"iaculis justo in hac habitasse platea dictumst etiam faucibus cursus"},
// {"product_name":"Porcupine, prehensile-tailed","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":3,"review_count":20,"price":3.96,"product_description":"at dolor quis odio consequat"},
// {"product_name":"Azara's zorro","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":5,"review_count":12,"price":129.09,"product_description":"gravida sem praesent id massa id nisl venenatis lacinia"},
// {"product_name":"Galapagos mockingbird","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":4,"review_count":18,"price":184.4,"product_description":"nulla dapibus dolor vel est"},
// {"product_name":"Bear, polar","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":5,"review_count":4,"price":156.59,"product_description":"primis in faucibus orci luctus et"},
// {"product_name":"Palm squirrel","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":3,"review_count":9,"price":23.38,"product_description":"nullam varius nulla facilisi cras non velit nec"},
// {"product_name":"Black-necked stork","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":1,"review_count":20,"price":42.45,"product_description":"vehicula consequat morbi a ipsum integer a nibh"},
// {"product_name":"Kangaroo, western grey","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":1,"review_count":12,"price":194.26,"product_description":"rutrum neque aenean auctor gravida"},
// {"product_name":"Macaque, japanese","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":2,"review_count":4,"price":35.26,"product_description":"velit donec diam neque vestibulum"},
// {"product_name":"Whale, killer","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":1,"review_count":18,"price":130.45,"product_description":"orci eget orci vehicula condimentum curabitur in"},
// {"product_name":"Asian elephant","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":3,"review_count":5,"price":64.27,"product_description":"augue vel accumsan tellus nisi eu orci mauris lacinia"},
// {"product_name":"Yellow-brown sungazer","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":5,"review_count":16,"price":110.75,"product_description":"nec sem duis aliquam convallis nunc proin"},
// {"product_name":"Gaur","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":4,"review_count":18,"price":53.12,"product_description":"mauris morbi non lectus aliquam sit amet diam in"},
// {"product_name":"Cape clawless otter","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":5,"review_count":7,"price":185.78,"product_description":"nullam varius nulla facilisi cras non velit nec nisi"},
// {"product_name":"American crow","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":5,"review_count":13,"price":43.46,"product_description":"penatibus et magnis dis parturient montes nascetur ridiculus mus etiam"},
// {"product_name":"Sloth, two-toed","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":5,"review_count":14,"price":8.1,"product_description":"massa donec dapibus duis at velit eu"},
// {"product_name":"Bat-eared fox","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":5,"review_count":18,"price":103.86,"product_description":"primis in faucibus orci luctus et ultrices posuere"},
// {"product_name":"Swainson's francolin","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":5,"review_count":15,"price":140.46,"product_description":"ante ipsum primis in faucibus"},
// {"product_name":"Painted stork","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":4,"review_count":20,"price":44.75,"product_description":"integer non velit donec diam neque vestibulum eget"},
// {"product_name":"Peccary, white-lipped","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":3,"review_count":16,"price":190.32,"product_description":"ultrices posuere cubilia curae donec pharetra magna"},
// {"product_name":"Laughing dove","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":1,"review_count":3,"price":94.38,"product_description":"eros suspendisse accumsan tortor quis turpis sed ante"},
// {"product_name":"Rattlesnake, eastern diamondback","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":3,"review_count":9,"price":160.43,"product_description":"vitae quam suspendisse potenti nullam porttitor"},
// {"product_name":"Mourning collared dove","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":5,"review_count":10,"price":63.45,"product_description":"nec euismod scelerisque quam turpis"},
// {"product_name":"Puma","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":1,"review_count":8,"price":92.26,"product_description":"eros viverra eget congue eget semper rutrum"},
// {"product_name":"Tammar wallaby","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":4,"review_count":2,"price":86.0,"product_description":"quis turpis eget elit sodales scelerisque"},
// {"product_name":"Elk, Wapiti","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":4,"review_count":2,"price":136.04,"product_description":"nibh in quis justo maecenas rhoncus aliquam"},
// {"product_name":"Robin, white-throated","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":5,"review_count":6,"price":86.83,"product_description":"aenean fermentum donec ut mauris eget massa tempor convallis nulla"},
// {"product_name":"Elephant, asian","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":2,"review_count":7,"price":117.03,"product_description":"pellentesque eget nunc donec quis orci eget orci vehicula condimentum"},
// {"product_name":"Common shelduck","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":4,"review_count":8,"price":56.82,"product_description":"neque aenean auctor gravida sem praesent id massa id nisl"},
// {"product_name":"Brown hyena","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":2,"review_count":10,"price":44.71,"product_description":"id sapien in sapien iaculis congue vivamus metus"},
// {"product_name":"Plover, three-banded","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":3,"review_count":11,"price":69.61,"product_description":"natoque penatibus et magnis dis parturient montes nascetur"},
// {"product_name":"Porcupine, crested","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":2,"review_count":20,"price":13.84,"product_description":"sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum"},
// {"product_name":"Zorro, common","image_src":"http://dummyimage.com/150x150.bmp/5fa2dd/ffffff","review_stars":1,"review_count":10,"price":81.64,"product_description":"parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum"},
// {"product_name":"Rhea, greater","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":2,"review_count":17,"price":1.35,"product_description":"consequat metus sapien ut nunc vestibulum ante ipsum primis in"},
// {"product_name":"Gull, lava","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":3,"review_count":19,"price":149.29,"product_description":"vestibulum vestibulum ante ipsum primis in faucibus orci luctus et"},
// {"product_name":"Bee-eater, white-fronted","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":2,"review_count":13,"price":182.24,"product_description":"vel nisl duis ac nibh fusce lacus purus aliquet"},
// {"product_name":"Little cormorant","image_src":"http://dummyimage.com/150x150.jpg/cc0000/ffffff","review_stars":5,"review_count":18,"price":111.35,"product_description":"congue etiam justo etiam pretium iaculis justo in hac"},
// {"product_name":"Glossy starling (unidentified)","image_src":"http://dummyimage.com/150x150.png/dddddd/000000","review_stars":4,"review_count":1,"price":99.82,"product_description":"ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus"},
// {"product_name":"Beaver, american","image_src":"http://dummyimage.com/150x150.bmp/ff4444/ffffff","review_stars":3,"review_count":20,"price":122.76,"product_description":"nonummy integer non velit donec diam"},
// {"product_name":"Greater adjutant stork","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":2,"review_count":10,"price":43.46,"product_description":"vel augue vestibulum ante ipsum"},
// {"product_name":"Squirrel, nelson ground","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":1,"review_count":19,"price":163.98,"product_description":"sapien urna pretium nisl ut volutpat sapien"},
// {"product_name":"American marten","image_src":"http://dummyimage.com/150x150.bmp/dddddd/000000","review_stars":5,"review_count":4,"price":161.25,"product_description":"leo maecenas pulvinar lobortis est phasellus sit"},
// {"product_name":"Wallaroo, common","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":2,"review_count":7,"price":91.9,"product_description":"in faucibus orci luctus et ultrices posuere cubilia curae duis"},
// {"product_name":"Tortoise, desert","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":3,"review_count":7,"price":139.72,"product_description":"pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus"},
// {"product_name":"Pygmy possum","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":4,"review_count":13,"price":24.41,"product_description":"sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus"},
// {"product_name":"Pintail, white-cheeked","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":4,"review_count":3,"price":189.55,"product_description":"ante vivamus tortor duis mattis egestas metus aenean fermentum"},
// {"product_name":"Ringtail cat","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":2,"review_count":3,"price":22.89,"product_description":"vestibulum vestibulum ante ipsum primis in faucibus orci luctus"},
// {"product_name":"Chameleon (unidentified)","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":4,"review_count":1,"price":132.13,"product_description":"aliquet pulvinar sed nisl nunc rhoncus"},
// {"product_name":"Eagle, crowned","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":2,"review_count":18,"price":50.4,"product_description":"nulla nisl nunc nisl duis bibendum felis sed"},
// {"product_name":"Goose, knob-nosed","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":4,"review_count":18,"price":77.47,"product_description":"eros vestibulum ac est lacinia"},
// {"product_name":"Cape white-eye","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":3,"review_count":18,"price":105.75,"product_description":"nulla elit ac nulla sed vel"},
// {"product_name":"Marmot, yellow-bellied","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":4,"review_count":6,"price":23.56,"product_description":"in hac habitasse platea dictumst"},
// {"product_name":"Hoffman's sloth","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":3,"review_count":1,"price":139.69,"product_description":"at velit eu est congue elementum in hac"},
// {"product_name":"Southern white-crowned shrike","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":3,"review_count":19,"price":19.58,"product_description":"suscipit ligula in lacus curabitur at ipsum"},
// {"product_name":"Fox, bat-eared","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":2,"review_count":8,"price":64.07,"product_description":"ridiculus mus etiam vel augue vestibulum rutrum"},
// {"product_name":"Macaw, scarlet","image_src":"http://dummyimage.com/150x150.jpg/ff4444/ffffff","review_stars":5,"review_count":5,"price":22.15,"product_description":"malesuada in imperdiet et commodo"},
// {"product_name":"Egret, cattle","image_src":"http://dummyimage.com/150x150.png/cc0000/ffffff","review_stars":1,"review_count":14,"price":55.85,"product_description":"ut dolor morbi vel lectus in quam fringilla rhoncus"},
// {"product_name":"Eastern white pelican","image_src":"http://dummyimage.com/150x150.png/ff4444/ffffff","review_stars":4,"review_count":1,"price":75.3,"product_description":"orci pede venenatis non sodales sed"},
// {"product_name":"Whip-tailed wallaby","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":4,"review_count":3,"price":199.91,"product_description":"elementum ligula vehicula consequat morbi a ipsum integer a nibh"},
// {"product_name":"Rhinoceros, black","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":5,"review_count":14,"price":168.08,"product_description":"vestibulum ante ipsum primis in faucibus orci luctus et"},
// {"product_name":"Four-spotted skimmer","image_src":"http://dummyimage.com/150x150.bmp/ff4444/ffffff","review_stars":2,"review_count":2,"price":75.09,"product_description":"nibh in quis justo maecenas rhoncus aliquam lacus"},
// {"product_name":"Red-legged pademelon","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":2,"review_count":1,"price":141.65,"product_description":"libero nullam sit amet turpis elementum ligula vehicula"},
// {"product_name":"Puma, south american","image_src":"http://dummyimage.com/150x150.bmp/cc0000/ffffff","review_stars":4,"review_count":9,"price":118.54,"product_description":"nonummy integer non velit donec diam neque vestibulum eget"},
// {"product_name":"Brolga crane","image_src":"http://dummyimage.com/150x150.jpg/dddddd/000000","review_stars":3,"review_count":3,"price":16.7,"product_description":"platea dictumst morbi vestibulum velit id pretium"},
// {"product_name":"Red meerkat","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":3,"review_count":1,"price":6.52,"product_description":"dapibus duis at velit eu est congue"},
// {"product_name":"Blue crane","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":3,"review_count":2,"price":104.82,"product_description":"viverra dapibus nulla suscipit ligula in lacus curabitur at"},
// {"product_name":"Brush-tailed phascogale","image_src":"http://dummyimage.com/150x150.jpg/5fa2dd/ffffff","review_stars":5,"review_count":3,"price":69.54,"product_description":"lectus in est risus auctor sed tristique in tempus"},
// {"product_name":"Squirrel, antelope ground","image_src":"http://dummyimage.com/150x150.png/5fa2dd/ffffff","review_stars":2,"review_count":18,"price":171.26,"product_description":"turpis eget elit sodales scelerisque mauris sit amet eros"}]



// //function to update mock data with product names from remyArr
// let remyArr = ["Hilti Orbital Sander", "Hilti Lathe", "Bosch Table Saw", "Bosch Power Screwdriver", "Dewalt Rotary Tool", "Bosch Shop Vacuum", "Hilti Nail Gun", "Craftsman Chop Saw", "Dewalt Jointer", "Hilti Chainsaw", "Bosch Reciprocating Saw", "Craftsman Circular Saw", "Bosch Angle Grinder", "Craftsman Heat Gun", "Bosch Jigsaw", "Hilti Chop Saw", "Craftsman Biscuit Joiner", "Bosch Biscuit Joiner", "Dewalt Table Saw", "Hilti Biscuit Joiner", "Bosch Miter Saw", "Hilti Hammer Drill", "Craftsman Disc Sander", "Craftsman Nail Gun", "Bosch Disc Sander", "Dewalt Scroll Saw", "Craftsman Miter Saw", "Craftsman Shop Vacuum", "Hilti Air Compressor", "Hilti Table Saw", "Dewalt Impact Driver", "Craftsman Jointer", "Craftsman Rotary Tool", "Hilti Jigsaw", "Bosch Rotary Tool", "Hilti Rotary Tool", "Hilti Shop Vacuum", "Craftsman Reciprocating Saw", "Hilti Miter Saw", "Craftsman Air Compressor", "Dewalt Biscuit Joiner", "Dewalt Radial Arm Saw", "Dewalt Disc Sander", "Bosch Belt Sander", "Dewalt Air Compressor", "Craftsman Chainsaw", "Hilti Radial Arm Saw", "Bosch Chainsaw", "Craftsman Jigsaw", "Bosch Circular Saw", "Bosch Hammer Drill", "Hilti Reciprocating Saw", "Dewalt Chop Saw", "Bosch Lathe", "Dewalt Impact Wrench", "Bosch Jointer", "Craftsman Lathe", "Craftsman Hammer Drill", "Bosch Air Compressor", "Hilti Disc Sander", "Craftsman Scroll Saw", "Dewalt Lathe", "Bosch Radial Arm Saw", "Dewalt Angle Grinder", "Bosch Scroll Saw", "Dewalt Nail Gun", "Hilti Angle Grinder", "Dewalt Power Screwdriver", "Hilti Heat Gun", "Craftsman Belt Sander", "Dewalt Orbital Sander", "Dewalt Belt Sander", "Hilti Scroll Saw", "Hilti Impact Driver", "Dewalt Shop Vacuum", "Dewalt Chainsaw", "Dewalt Reciprocating Saw", "Hilti Power Screwdriver", "Craftsman Power Screwdriver", "Craftsman Impact Driver", "Craftsman Table Saw", "Dewalt Jigsaw", "Dewalt Heat Gun", "Hilti Belt Sander", "Dewalt Hammer Drill", "Hilti Jointer", "Bosch Heat Gun", "Craftsman Angle Grinder", "Hilti Impact Wrench", "Craftsman Impact Wrench", "Craftsman Radial Arm Saw", "Dewalt Circular Saw", "Bosch Orbital Sander", "Bosch Nail Gun", "Craftsman Orbital Sander", "Bosch Chop Saw", "Bosch Impact Wrench", "Bosch Impact Driver", "Hilti Circular Saw", "Dewalt Miter Saw"]
// data.forEach(function (product, index) {
//     product.product_name = remyArr[index];
// })
// console.log('new data is: ', data);

