const data = [ { product_name: 'Hilti Orbital Sander',image_src: 'http://dummyimage.com/209x229.jpg/ff4444/ffffff',review_stars: 2,review_count: 27,price: 26.95,product_description: 'interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu' },
{ product_name: 'Hilti Lathe',
image_src: 'http://dummyimage.com/114x172.bmp/cc0000/ffffff',
review_stars: 3,
review_count: 20,
price: 53.10,
product_description:
 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum' },
{ product_name: 'Bosch Table Saw',
image_src: 'http://dummyimage.com/222x151.bmp/ff4444/ffffff',
review_stars: 1,
review_count: 13,
price: 25.35,
product_description:
 'vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus' },
{ product_name: 'Bosch Power Screwdriver',
image_src: 'http://dummyimage.com/148x138.bmp/cc0000/ffffff',
review_stars: 2,
review_count: 14,
price: 27.62,
product_description:
 'pede justo eu massa donec dapibus duis at velit eu est congue elementum' },
{ product_name: 'Dewalt Rotary Tool',
image_src: 'http://dummyimage.com/168x121.png/ff4444/ffffff',
review_stars: 3,
review_count: 11,
price: 37.26,
product_description:
 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non' },
{ product_name: 'Bosch Shop Vacuum',
image_src: 'http://dummyimage.com/205x132.bmp/5fa2dd/ffffff',
review_stars: 5,
review_count: 27,
price: 63.65,
product_description:
 'turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien' },
{ product_name: 'Hilti Nail Gun',
image_src: 'http://dummyimage.com/223x193.png/dddddd/000000',
review_stars: 5,
review_count: 13,
price: 24.20,
product_description:
 'aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque' },
{ product_name: 'Craftsman Chop Saw',
image_src: 'http://dummyimage.com/132x188.jpg/5fa2dd/ffffff',
review_stars: 2,
review_count: 5,
price: 61.89,
product_description:
 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi' },
{ product_name: 'Dewalt Jointer',
image_src: 'http://dummyimage.com/174x212.jpg/cc0000/ffffff',
review_stars: 5,
review_count: 22,
price: 50.10,
product_description:
 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis' },
{ product_name: 'Hilti Chainsaw',
image_src: 'http://dummyimage.com/227x210.png/dddddd/000000',
review_stars: 5,
review_count: 2,
price: 78.33,
product_description:
 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa' },
{ product_name: 'Bosch Reciprocating Saw',
image_src: 'http://dummyimage.com/196x170.bmp/cc0000/ffffff',
review_stars: 2,
review_count: 4,
price: 43.34,
product_description:
 'amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas' },
{ product_name: 'Craftsman Circular Saw',
image_src: 'http://dummyimage.com/246x154.bmp/ff4444/ffffff',
review_stars: 1,
review_count: 21,
price: 4.60,
product_description:
 'vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi' },
{ product_name: 'Bosch Angle Grinder',
image_src: 'http://dummyimage.com/232x206.png/ff4444/ffffff',
review_stars: 3,
review_count: 12,
price: 29.04,
product_description:
 'orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer' },
{ product_name: 'Craftsman Heat Gun',
image_src: 'http://dummyimage.com/234x181.jpg/5fa2dd/ffffff',
review_stars: 2,
review_count: 28,
price: 7.96,
product_description:
 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae' },
{ product_name: 'Bosch Jigsaw',
image_src: 'http://dummyimage.com/135x121.png/ff4444/ffffff',
review_stars: 5,
review_count: 31,
price: 11.49,
product_description:
 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis' },
{ product_name: 'Hilti Chop Saw',
image_src: 'http://dummyimage.com/133x215.png/cc0000/ffffff',
review_stars: 2,
review_count: 20,
price: 41.06,
product_description:
 'neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante' },
{ product_name: 'Craftsman Biscuit Joiner',
image_src: 'http://dummyimage.com/239x129.jpg/dddddd/000000',
review_stars: 2,
review_count: 26,
price: 28.56,
product_description:
 'justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus' },
{ product_name: 'Bosch Biscuit Joiner',
image_src: 'http://dummyimage.com/136x181.jpg/ff4444/ffffff',
review_stars: 3,
review_count: 26,
price: 23.62,
product_description:
 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed' },
{ product_name: 'Dewalt Table Saw',
image_src: 'http://dummyimage.com/163x185.bmp/dddddd/000000',
review_stars: 3,
review_count: 28,
price: 12.66,
product_description:
 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim' },
{ product_name: 'Hilti Biscuit Joiner',
image_src: 'http://dummyimage.com/245x231.png/dddddd/000000',
review_stars: 1,
review_count: 38,
price: 24.16,
product_description:
 'semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac' },
{ product_name: 'Bosch Miter Saw',
image_src: 'http://dummyimage.com/122x206.bmp/dddddd/000000',
review_stars: 2,
review_count: 22,
price: 2.61,
product_description:
 'nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus' },
{ product_name: 'Hilti Hammer Drill',
image_src: 'http://dummyimage.com/130x234.bmp/5fa2dd/ffffff',
review_stars: 3,
review_count: 2,
price: 75.04,
product_description:
 'ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue diam id' },
{ product_name: 'Craftsman Disc Sander',
image_src: 'http://dummyimage.com/138x147.png/ff4444/ffffff',
review_stars: 1,
review_count: 1,
price: 75.46,
product_description:
 'accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit' },
{ product_name: 'Craftsman Nail Gun',
image_src: 'http://dummyimage.com/209x239.png/5fa2dd/ffffff',
review_stars: 4,
review_count: 24,
price: 40.20,
product_description:
 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in' },
{ product_name: 'Bosch Disc Sander',
image_src: 'http://dummyimage.com/228x149.jpg/ff4444/ffffff',
review_stars: 3,
review_count: 11,
price: 33.28,
product_description:
 'at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non' },
{ product_name: 'Dewalt Scroll Saw',
image_src: 'http://dummyimage.com/142x179.png/5fa2dd/ffffff',
review_stars: 5,
review_count: 21,
price: 60.85,
product_description:
 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam' },
{ product_name: 'Craftsman Miter Saw',
image_src: 'http://dummyimage.com/126x121.png/dddddd/000000',
review_stars: 3,
review_count: 26,
price: 32.45,
product_description:
 'non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante' },
{ product_name: 'Craftsman Shop Vacuum',
image_src: 'http://dummyimage.com/110x148.png/cc0000/ffffff',
review_stars: 2,
review_count: 1,
price: 41.87,
product_description:
 'lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae' },
{ product_name: 'Hilti Air Compressor',
image_src: 'http://dummyimage.com/246x248.jpg/dddddd/000000',
review_stars: 1,
review_count: 24,
price: 2.59,
product_description:
 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec' },
{ product_name: 'Hilti Table Saw',
image_src: 'http://dummyimage.com/150x196.bmp/cc0000/ffffff',
review_stars: 1,
review_count: 5,
price: 29.69,
product_description:
 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede' },
{ product_name: 'Dewalt Impact Driver',
image_src: 'http://dummyimage.com/229x171.png/cc0000/ffffff',
review_stars: 3,
review_count: 31,
price: 31.08,
product_description:
 'convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien' },
{ product_name: 'Craftsman Jointer',
image_src: 'http://dummyimage.com/174x143.bmp/ff4444/ffffff',
review_stars: 3,
review_count: 9,
price: 78.93,
product_description:
 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit' },
{ product_name: 'Craftsman Rotary Tool',
image_src: 'http://dummyimage.com/160x208.jpg/5fa2dd/ffffff',
review_stars: 4,
review_count: 6,
price: 11.07,
product_description:
 'ac est lacinia nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu' },
{ product_name: 'Hilti Jigsaw',
image_src: 'http://dummyimage.com/213x157.png/dddddd/000000',
review_stars: 5,
review_count: 2,
price: 34.14,
product_description:
 'aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus' },
{ product_name: 'Bosch Rotary Tool',
image_src: 'http://dummyimage.com/118x138.png/cc0000/ffffff',
review_stars: 3,
review_count: 33,
price: 17.93,
product_description: 'turpis enim blandit mi in porttitor pede justo eu massa' },
{ product_name: 'Hilti Rotary Tool',
image_src: 'http://dummyimage.com/202x175.bmp/5fa2dd/ffffff',
review_stars: 3,
review_count: 15,
price: 60.53,
product_description:
 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula' },
{ product_name: 'Hilti Shop Vacuum',
image_src: 'http://dummyimage.com/189x114.png/dddddd/000000',
review_stars: 4,
review_count: 3,
price: 74.28,
product_description:
 'scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis' },
{ product_name: 'Craftsman Reciprocating Saw',
image_src: 'http://dummyimage.com/154x189.png/dddddd/000000',
review_stars: 3,
review_count: 25,
price: 78.96,
product_description:
 'ut rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus' },
{ product_name: 'Hilti Miter Saw',
image_src: 'http://dummyimage.com/228x164.bmp/5fa2dd/ffffff',
review_stars: 4,
review_count: 34,
price: 70.03,
product_description:
 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id' },
{ product_name: 'Craftsman Air Compressor',
image_src: 'http://dummyimage.com/126x224.bmp/ff4444/ffffff',
review_stars: 2,
review_count: 22,
price: 9.77,
product_description:
 'sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula' },
{ product_name: 'Dewalt Biscuit Joiner',
image_src: 'http://dummyimage.com/239x174.jpg/5fa2dd/ffffff',
review_stars: 4,
review_count: 3,
price: 8.39,
product_description:
 'ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat' },
{ product_name: 'Dewalt Radial Arm Saw',
image_src: 'http://dummyimage.com/147x151.bmp/5fa2dd/ffffff',
review_stars: 5,
review_count: 28,
price: 9.26,
product_description:
 'scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean' },
{ product_name: 'Dewalt Disc Sander',
image_src: 'http://dummyimage.com/162x175.png/5fa2dd/ffffff',
review_stars: 4,
review_count: 11,
price: 74.43,
product_description:
 'rutrum nulla nunc purus phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat' },
{ product_name: 'Bosch Belt Sander',
image_src: 'http://dummyimage.com/202x176.png/5fa2dd/ffffff',
review_stars: 2,
review_count: 28,
price: 57.67,
product_description:
 'erat eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien' },
{ product_name: 'Dewalt Air Compressor',
image_src: 'http://dummyimage.com/115x123.png/5fa2dd/ffffff',
review_stars: 1,
review_count: 22,
price: 1.31,
product_description:
 'quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar' },
{ product_name: 'Craftsman Chainsaw',
image_src: 'http://dummyimage.com/244x167.png/cc0000/ffffff',
review_stars: 5,
review_count: 31,
price: 32.15,
product_description:
 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum' },
{ product_name: 'Hilti Radial Arm Saw',
image_src: 'http://dummyimage.com/171x180.jpg/dddddd/000000',
review_stars: 4,
review_count: 3,
price: 10.06,
product_description:
 'aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet et commodo' },
{ product_name: 'Bosch Chainsaw',
image_src: 'http://dummyimage.com/226x242.png/ff4444/ffffff',
review_stars: 2,
review_count: 29,
price: 34.18,
product_description:
 'suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non' },
{ product_name: 'Craftsman Jigsaw',
image_src: 'http://dummyimage.com/151x164.jpg/cc0000/ffffff',
review_stars: 4,
review_count: 18,
price: 35.03,
product_description:
 'rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia' },
{ product_name: 'Bosch Circular Saw',
image_src: 'http://dummyimage.com/197x207.bmp/5fa2dd/ffffff',
review_stars: 3,
review_count: 38,
price: 10.13,
product_description:
 'pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse platea dictumst' },
{ product_name: 'Bosch Hammer Drill',
image_src: 'http://dummyimage.com/108x134.bmp/5fa2dd/ffffff',
review_stars: 2,
review_count: 14,
price: 38.10,
product_description:
 'ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero' },
{ product_name: 'Hilti Reciprocating Saw',
image_src: 'http://dummyimage.com/115x155.png/cc0000/ffffff',
review_stars: 3,
review_count: 4,
price: 7.71,
product_description:
 'rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue' },
{ product_name: 'Dewalt Chop Saw',
image_src: 'http://dummyimage.com/232x147.bmp/5fa2dd/ffffff',
review_stars: 3,
review_count: 40,
price: 45.67,
product_description:
 'eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras' },
{ product_name: 'Bosch Lathe',
image_src: 'http://dummyimage.com/105x134.jpg/5fa2dd/ffffff',
review_stars: 5,
review_count: 27,
price: 18.22,
product_description:
 'morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed' },
{ product_name: 'Dewalt Impact Wrench',
image_src: 'http://dummyimage.com/188x206.jpg/dddddd/000000',
review_stars: 2,
review_count: 2,
price: 63.73,
product_description:
 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum' },
{ product_name: 'Bosch Jointer',
image_src: 'http://dummyimage.com/206x175.bmp/dddddd/000000',
review_stars: 5,
review_count: 26,
price: 77.88,
product_description:
 'ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem' },
{ product_name: 'Craftsman Lathe',
image_src: 'http://dummyimage.com/184x180.bmp/cc0000/ffffff',
review_stars: 1,
review_count: 19,
price: 67.84,
product_description:
 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit' },
{ product_name: 'Craftsman Hammer Drill',
image_src: 'http://dummyimage.com/199x238.bmp/5fa2dd/ffffff',
review_stars: 1,
review_count: 12,
price: 39.40,
product_description:
 'potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus' },
{ product_name: 'Bosch Air Compressor',
image_src: 'http://dummyimage.com/168x128.jpg/dddddd/000000',
review_stars: 1,
review_count: 7,
price: 26.40,
product_description:
 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula' },
{ product_name: 'Hilti Disc Sander',
image_src: 'http://dummyimage.com/150x106.jpg/ff4444/ffffff',
review_stars: 2,
review_count: 12,
price: 57.51,
product_description:
 'suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis' },
{ product_name: 'Craftsman Scroll Saw',
image_src: 'http://dummyimage.com/102x236.png/ff4444/ffffff',
review_stars: 3,
review_count: 36,
price: 25.50,
product_description:
 'donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies' },
{ product_name: 'Dewalt Lathe',
image_src: 'http://dummyimage.com/124x195.bmp/dddddd/000000',
review_stars: 4,
review_count: 6,
price: 73.45,
product_description:
 'convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci' },
{ product_name: 'Bosch Radial Arm Saw',
image_src: 'http://dummyimage.com/200x240.png/ff4444/ffffff',
review_stars: 5,
review_count: 6,
price: 65.15,
product_description:
 'quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a' },
{ product_name: 'Dewalt Angle Grinder',
image_src: 'http://dummyimage.com/210x236.bmp/cc0000/ffffff',
review_stars: 5,
review_count: 9,
price: 20.08,
product_description:
 'donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna' },
{ product_name: 'Bosch Scroll Saw',
image_src: 'http://dummyimage.com/203x135.bmp/cc0000/ffffff',
review_stars: 2,
review_count: 1,
price: 35.44,
product_description:
 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit' },
{ product_name: 'Dewalt Nail Gun',
image_src: 'http://dummyimage.com/120x133.jpg/ff4444/ffffff',
review_stars: 5,
review_count: 39,
price: 23.01,
product_description:
 'et tempus semper est quam pharetra magna ac consequat metus sapien' },
{ product_name: 'Hilti Angle Grinder',
image_src: 'http://dummyimage.com/107x206.bmp/cc0000/ffffff',
review_stars: 3,
review_count: 21,
price: 21.75,
product_description:
 'morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique' },
{ product_name: 'Dewalt Power Screwdriver',
image_src: 'http://dummyimage.com/106x212.bmp/ff4444/ffffff',
review_stars: 1,
review_count: 6,
price: 36.11,
product_description:
 'commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing' },
{ product_name: 'Hilti Heat Gun',
image_src: 'http://dummyimage.com/147x164.bmp/ff4444/ffffff',
review_stars: 5,
review_count: 36,
price: 44.90,
product_description:
 'rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec' },
{ product_name: 'Craftsman Belt Sander',
image_src: 'http://dummyimage.com/148x176.jpg/ff4444/ffffff',
review_stars: 2,
review_count: 6,
price: 20.64,
product_description:
 'erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu' },
{ product_name: 'Dewalt Orbital Sander',
image_src: 'http://dummyimage.com/236x143.bmp/5fa2dd/ffffff',
review_stars: 5,
review_count: 22,
price: 63.72,
product_description:
 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra' },
{ product_name: 'Dewalt Belt Sander',
image_src: 'http://dummyimage.com/239x235.bmp/5fa2dd/ffffff',
review_stars: 5,
review_count: 5,
price: 42.89,
product_description:
 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu' },
{ product_name: 'Hilti Scroll Saw',
image_src: 'http://dummyimage.com/245x136.png/ff4444/ffffff',
review_stars: 2,
review_count: 39,
price: 36.59,
product_description:
 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam' },
{ product_name: 'Hilti Impact Driver',
image_src: 'http://dummyimage.com/111x234.png/dddddd/000000',
review_stars: 4,
review_count: 25,
price: 67.06,
product_description:
 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem' },
{ product_name: 'Dewalt Shop Vacuum',
image_src: 'http://dummyimage.com/209x182.png/ff4444/ffffff',
review_stars: 5,
review_count: 38,
price: 22.77,
product_description:
 'nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce' },
{ product_name: 'Dewalt Chainsaw',
image_src: 'http://dummyimage.com/136x182.png/ff4444/ffffff',
review_stars: 2,
review_count: 6,
price: 28.66,
product_description:
 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl' },
{ product_name: 'Dewalt Reciprocating Saw',
image_src: 'http://dummyimage.com/138x176.png/ff4444/ffffff',
review_stars: 5,
review_count: 30,
price: 24.32,
product_description:
 'porta volutpat quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at' },
{ product_name: 'Hilti Power Screwdriver',
image_src: 'http://dummyimage.com/132x127.jpg/5fa2dd/ffffff',
review_stars: 4,
review_count: 33,
price: 71.15,
product_description:
 'at dolor quis odio consequat varius integer ac leo pellentesque ultrices' },
{ product_name: 'Craftsman Power Screwdriver',
image_src: 'http://dummyimage.com/172x175.png/5fa2dd/ffffff',
review_stars: 1,
review_count: 33,
price: 24.21,
product_description:
 'felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo' },
{ product_name: 'Craftsman Impact Driver',
image_src: 'http://dummyimage.com/128x148.png/5fa2dd/ffffff',
review_stars: 3,
review_count: 4,
price: 65.33,
product_description:
 'ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan' },
{ product_name: 'Craftsman Table Saw',
image_src: 'http://dummyimage.com/158x142.jpg/ff4444/ffffff',
review_stars: 3,
review_count: 39,
price: 61.94,
product_description:
 'blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in' },
{ product_name: 'Dewalt Jigsaw',
image_src: 'http://dummyimage.com/114x123.jpg/dddddd/000000',
review_stars: 2,
review_count: 25,
price: 79.56,
product_description:
 'sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique' },
{ product_name: 'Dewalt Heat Gun',
image_src: 'http://dummyimage.com/223x243.jpg/dddddd/000000',
review_stars: 4,
review_count: 21,
price: 7.85,
product_description:
 'pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus' },
{ product_name: 'Hilti Belt Sander',
image_src: 'http://dummyimage.com/114x116.jpg/ff4444/ffffff',
review_stars: 4,
review_count: 24,
price: 47.78,
product_description:
 'nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet' },
{ product_name: 'Dewalt Hammer Drill',
image_src: 'http://dummyimage.com/119x159.png/dddddd/000000',
review_stars: 5,
review_count: 17,
price: 17.56,
product_description:
 'vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula' },
{ product_name: 'Hilti Jointer',
image_src: 'http://dummyimage.com/218x209.bmp/ff4444/ffffff',
review_stars: 3,
review_count: 24,
price: 45.05,
product_description:
 'turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan' },
{ product_name: 'Bosch Heat Gun',
image_src: 'http://dummyimage.com/142x105.png/cc0000/ffffff',
review_stars: 2,
review_count: 8,
price: 7.92,
product_description:
 'sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum' },
{ product_name: 'Craftsman Angle Grinder',
image_src: 'http://dummyimage.com/167x131.bmp/5fa2dd/ffffff',
review_stars: 2,
review_count: 5,
price: 70.23,
product_description:
 'leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus' },
{ product_name: 'Hilti Impact Wrench',
image_src: 'http://dummyimage.com/163x180.bmp/cc0000/ffffff',
review_stars: 5,
review_count: 18,
price: 79.85,
product_description:
 'et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin' },
{ product_name: 'Craftsman Impact Wrench',
image_src: 'http://dummyimage.com/213x148.jpg/ff4444/ffffff',
review_stars: 1,
review_count: 28,
price: 24.44,
product_description:
 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue' },
{ product_name: 'Craftsman Radial Arm Saw',
image_src: 'http://dummyimage.com/113x182.png/5fa2dd/ffffff',
review_stars: 3,
review_count: 37,
price: 15.84,
product_description:
 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio' },
{ product_name: 'Dewalt Circular Saw',
image_src: 'http://dummyimage.com/166x132.png/dddddd/000000',
review_stars: 3,
review_count: 14,
price: 17.62,
product_description:
 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo' },
{ product_name: 'Bosch Orbital Sander',
image_src: 'http://dummyimage.com/100x224.png/5fa2dd/ffffff',
review_stars: 3,
review_count: 37,
price: 76.59,
product_description:
 'arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis' },
{ product_name: 'Bosch Nail Gun',
image_src: 'http://dummyimage.com/206x195.jpg/dddddd/000000',
review_stars: 4,
review_count: 37,
price: 38.81,
product_description:
 'est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue' },
{ product_name: 'Craftsman Orbital Sander',
image_src: 'http://dummyimage.com/213x122.jpg/dddddd/000000',
review_stars: 4,
review_count: 24,
price: 32.03,
product_description:
 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio' },
{ product_name: 'Bosch Chop Saw',
image_src: 'http://dummyimage.com/187x222.bmp/5fa2dd/ffffff',
review_stars: 4,
review_count: 38,
price: 3.21,
product_description:
 'pellentesque at nulla suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient' },
{ product_name: 'Bosch Impact Wrench',
image_src: 'http://dummyimage.com/125x214.png/cc0000/ffffff',
review_stars: 5,
review_count: 11,
price: 34.69,
product_description: 'consequat ut nulla sed accumsan felis ut at dolor quis' },
{ product_name: 'Bosch Impact Driver',
image_src: 'http://dummyimage.com/193x100.png/dddddd/000000',
review_stars: 5,
review_count: 14,
price: 51.75,
product_description:
 'porttitor id consequat in consequat ut nulla sed accumsan felis' },
{ product_name: 'Hilti Circular Saw',
image_src: 'http://dummyimage.com/134x100.png/cc0000/ffffff',
review_stars: 3,
review_count: 6,
price: 29.11,
product_description:
 'augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum' },
{ product_name: 'Dewalt Miter Saw',
image_src: 'http://dummyimage.com/137x167.jpg/ff4444/ffffff',
review_stars: 5,
review_count: 36,
price: 31.55,
product_description:
 'mi nulla ac enim in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem' } ]

module.exports = data;